packages:
  - apps/*
  - tools/*
  - packages/*

catalog:
  '@t3-oss/env-core': ^0.13.8
  '@tanstack/react-form': ^1.23.0
  '@types/bun': ^1.2.22
  '@types/node': ^24.5.2
  better-auth: ^1.3.12
  hono: ^4.8.5
  lucide-react: 0.544.0
  next-themes: ^0.4.6
  superjson: ^2.2.2
  type-fest: ^4.41.0
  typescript: 5.9.2
  use-intl: ^4.3.9
  zod: 4.1.9
  zustand: ^5.0.6

catalogs:
  drizzle:
    '@types/pg': ^8.15.5
    drizzle-kit: 1.0.0-beta.1-c0277c0
    drizzle-orm: 1.0.0-beta.1-c0277c0
    pg: ^8.16.3
  react:
    '@types/react': ^19.1.13
    '@types/react-dom': ^19.1.9
    react: ^19.1.1
    react-dom: ^19.1.1
  tailwind:
    '@tailwindcss/vite': ^4.1.13
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.13
    tw-animate-css: ^1.3.8
  trpc:
    '@tanstack/react-query': ^5.89.0
    '@trpc/client': ^11.5.1
    '@trpc/server': ^11.5.1
    '@trpc/tanstack-react-query': ^11.5.1
  vite:
    '@tanstack/react-router': ^1.131.47
    '@tanstack/react-router-ssr-query': ^1.131.47
    '@tanstack/react-start': ^1.131.47
    '@tanstack/router-plugin': ^1.131.47
    '@vitejs/plugin-react': ^5.0.3
    vite: ^7.1.6
    vite-tsconfig-paths: ^5.1.4

minimumReleaseAge: 1440

publicHoistPattern:
  - '*prettier*'
  - eslint
