/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125AppRouteRouteImport } from './routes/{-$locale}/app/route'
import { Route as Char123LocaleChar125publicRouteRouteImport } from './routes/{-$locale}/(public)/route'
import { Route as Char123LocaleChar125AppIndexRouteImport } from './routes/{-$locale}/app/index'
import { Route as Char123LocaleChar125publicIndexRouteImport } from './routes/{-$locale}/(public)/index'
import { Route as Char123LocaleChar125AppSharedWishlistsRouteImport } from './routes/{-$locale}/app/shared-wishlists'
import { Route as Char123LocaleChar125AppSettingsRouteImport } from './routes/{-$locale}/app/settings'
import { Route as Char123LocaleChar125AppAccountRouteImport } from './routes/{-$locale}/app/account'
import { Route as Char123LocaleChar125publicLoginRouteImport } from './routes/{-$locale}/(public)/login'
import { Route as Char123LocaleChar125AppWishlistsIndexRouteImport } from './routes/{-$locale}/app/wishlists/index'
import { Route as Char123LocaleChar125AppWishlistsIdRouteImport } from './routes/{-$locale}/app/wishlists/$id'
import { ServerRoute as TrpcSplatServerRouteImport } from './routes/trpc.$'
import { ServerRoute as AuthSplatServerRouteImport } from './routes/auth.$'

const rootServerRouteImport = createServerRootRoute()

const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AppRouteRoute =
  Char123LocaleChar125AppRouteRouteImport.update({
    id: '/app',
    path: '/app',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125publicRouteRoute =
  Char123LocaleChar125publicRouteRouteImport.update({
    id: '/(public)',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125AppIndexRoute =
  Char123LocaleChar125AppIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125AppRouteRoute,
  } as any)
const Char123LocaleChar125publicIndexRoute =
  Char123LocaleChar125publicIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125publicRouteRoute,
  } as any)
const Char123LocaleChar125AppSharedWishlistsRoute =
  Char123LocaleChar125AppSharedWishlistsRouteImport.update({
    id: '/shared-wishlists',
    path: '/shared-wishlists',
    getParentRoute: () => Char123LocaleChar125AppRouteRoute,
  } as any)
const Char123LocaleChar125AppSettingsRoute =
  Char123LocaleChar125AppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => Char123LocaleChar125AppRouteRoute,
  } as any)
const Char123LocaleChar125AppAccountRoute =
  Char123LocaleChar125AppAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => Char123LocaleChar125AppRouteRoute,
  } as any)
const Char123LocaleChar125publicLoginRoute =
  Char123LocaleChar125publicLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => Char123LocaleChar125publicRouteRoute,
  } as any)
const Char123LocaleChar125AppWishlistsIndexRoute =
  Char123LocaleChar125AppWishlistsIndexRouteImport.update({
    id: '/wishlists/',
    path: '/wishlists/',
    getParentRoute: () => Char123LocaleChar125AppRouteRoute,
  } as any)
const Char123LocaleChar125AppWishlistsIdRoute =
  Char123LocaleChar125AppWishlistsIdRouteImport.update({
    id: '/wishlists/$id',
    path: '/wishlists/$id',
    getParentRoute: () => Char123LocaleChar125AppRouteRoute,
  } as any)
const TrpcSplatServerRoute = TrpcSplatServerRouteImport.update({
  id: '/trpc/$',
  path: '/trpc/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const AuthSplatServerRoute = AuthSplatServerRouteImport.update({
  id: '/auth/$',
  path: '/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/': typeof Char123LocaleChar125publicIndexRoute
  '/{-$locale}/app': typeof Char123LocaleChar125AppRouteRouteWithChildren
  '/{-$locale}/login': typeof Char123LocaleChar125publicLoginRoute
  '/{-$locale}/app/account': typeof Char123LocaleChar125AppAccountRoute
  '/{-$locale}/app/settings': typeof Char123LocaleChar125AppSettingsRoute
  '/{-$locale}/app/shared-wishlists': typeof Char123LocaleChar125AppSharedWishlistsRoute
  '/{-$locale}/app/': typeof Char123LocaleChar125AppIndexRoute
  '/{-$locale}/app/wishlists/$id': typeof Char123LocaleChar125AppWishlistsIdRoute
  '/{-$locale}/app/wishlists': typeof Char123LocaleChar125AppWishlistsIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}/login': typeof Char123LocaleChar125publicLoginRoute
  '/{-$locale}/app/account': typeof Char123LocaleChar125AppAccountRoute
  '/{-$locale}/app/settings': typeof Char123LocaleChar125AppSettingsRoute
  '/{-$locale}/app/shared-wishlists': typeof Char123LocaleChar125AppSharedWishlistsRoute
  '/{-$locale}': typeof Char123LocaleChar125publicIndexRoute
  '/{-$locale}/app': typeof Char123LocaleChar125AppIndexRoute
  '/{-$locale}/app/wishlists/$id': typeof Char123LocaleChar125AppWishlistsIdRoute
  '/{-$locale}/app/wishlists': typeof Char123LocaleChar125AppWishlistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/{-$locale}/(public)': typeof Char123LocaleChar125publicRouteRouteWithChildren
  '/{-$locale}/app': typeof Char123LocaleChar125AppRouteRouteWithChildren
  '/{-$locale}/(public)/login': typeof Char123LocaleChar125publicLoginRoute
  '/{-$locale}/app/account': typeof Char123LocaleChar125AppAccountRoute
  '/{-$locale}/app/settings': typeof Char123LocaleChar125AppSettingsRoute
  '/{-$locale}/app/shared-wishlists': typeof Char123LocaleChar125AppSharedWishlistsRoute
  '/{-$locale}/(public)/': typeof Char123LocaleChar125publicIndexRoute
  '/{-$locale}/app/': typeof Char123LocaleChar125AppIndexRoute
  '/{-$locale}/app/wishlists/$id': typeof Char123LocaleChar125AppWishlistsIdRoute
  '/{-$locale}/app/wishlists/': typeof Char123LocaleChar125AppWishlistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/'
    | '/{-$locale}/app'
    | '/{-$locale}/login'
    | '/{-$locale}/app/account'
    | '/{-$locale}/app/settings'
    | '/{-$locale}/app/shared-wishlists'
    | '/{-$locale}/app/'
    | '/{-$locale}/app/wishlists/$id'
    | '/{-$locale}/app/wishlists'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}/login'
    | '/{-$locale}/app/account'
    | '/{-$locale}/app/settings'
    | '/{-$locale}/app/shared-wishlists'
    | '/{-$locale}'
    | '/{-$locale}/app'
    | '/{-$locale}/app/wishlists/$id'
    | '/{-$locale}/app/wishlists'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/(public)'
    | '/{-$locale}/app'
    | '/{-$locale}/(public)/login'
    | '/{-$locale}/app/account'
    | '/{-$locale}/app/settings'
    | '/{-$locale}/app/shared-wishlists'
    | '/{-$locale}/(public)/'
    | '/{-$locale}/app/'
    | '/{-$locale}/app/wishlists/$id'
    | '/{-$locale}/app/wishlists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
}
export interface FileServerRoutesByFullPath {
  '/auth/$': typeof AuthSplatServerRoute
  '/trpc/$': typeof TrpcSplatServerRoute
}
export interface FileServerRoutesByTo {
  '/auth/$': typeof AuthSplatServerRoute
  '/trpc/$': typeof TrpcSplatServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/auth/$': typeof AuthSplatServerRoute
  '/trpc/$': typeof TrpcSplatServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/auth/$' | '/trpc/$'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/auth/$' | '/trpc/$'
  id: '__root__' | '/auth/$' | '/trpc/$'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  AuthSplatServerRoute: typeof AuthSplatServerRoute
  TrpcSplatServerRoute: typeof TrpcSplatServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/app': {
      id: '/{-$locale}/app'
      path: '/app'
      fullPath: '/{-$locale}/app'
      preLoaderRoute: typeof Char123LocaleChar125AppRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(public)': {
      id: '/{-$locale}/(public)'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125publicRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/app/': {
      id: '/{-$locale}/app/'
      path: '/'
      fullPath: '/{-$locale}/app/'
      preLoaderRoute: typeof Char123LocaleChar125AppIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AppRouteRoute
    }
    '/{-$locale}/(public)/': {
      id: '/{-$locale}/(public)/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125publicIndexRouteImport
      parentRoute: typeof Char123LocaleChar125publicRouteRoute
    }
    '/{-$locale}/app/shared-wishlists': {
      id: '/{-$locale}/app/shared-wishlists'
      path: '/shared-wishlists'
      fullPath: '/{-$locale}/app/shared-wishlists'
      preLoaderRoute: typeof Char123LocaleChar125AppSharedWishlistsRouteImport
      parentRoute: typeof Char123LocaleChar125AppRouteRoute
    }
    '/{-$locale}/app/settings': {
      id: '/{-$locale}/app/settings'
      path: '/settings'
      fullPath: '/{-$locale}/app/settings'
      preLoaderRoute: typeof Char123LocaleChar125AppSettingsRouteImport
      parentRoute: typeof Char123LocaleChar125AppRouteRoute
    }
    '/{-$locale}/app/account': {
      id: '/{-$locale}/app/account'
      path: '/account'
      fullPath: '/{-$locale}/app/account'
      preLoaderRoute: typeof Char123LocaleChar125AppAccountRouteImport
      parentRoute: typeof Char123LocaleChar125AppRouteRoute
    }
    '/{-$locale}/(public)/login': {
      id: '/{-$locale}/(public)/login'
      path: '/login'
      fullPath: '/{-$locale}/login'
      preLoaderRoute: typeof Char123LocaleChar125publicLoginRouteImport
      parentRoute: typeof Char123LocaleChar125publicRouteRoute
    }
    '/{-$locale}/app/wishlists/': {
      id: '/{-$locale}/app/wishlists/'
      path: '/wishlists'
      fullPath: '/{-$locale}/app/wishlists'
      preLoaderRoute: typeof Char123LocaleChar125AppWishlistsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125AppRouteRoute
    }
    '/{-$locale}/app/wishlists/$id': {
      id: '/{-$locale}/app/wishlists/$id'
      path: '/wishlists/$id'
      fullPath: '/{-$locale}/app/wishlists/$id'
      preLoaderRoute: typeof Char123LocaleChar125AppWishlistsIdRouteImport
      parentRoute: typeof Char123LocaleChar125AppRouteRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/trpc/$': {
      id: '/trpc/$'
      path: '/trpc/$'
      fullPath: '/trpc/$'
      preLoaderRoute: typeof TrpcSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/auth/$': {
      id: '/auth/$'
      path: '/auth/$'
      fullPath: '/auth/$'
      preLoaderRoute: typeof AuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface Char123LocaleChar125publicRouteRouteChildren {
  Char123LocaleChar125publicLoginRoute: typeof Char123LocaleChar125publicLoginRoute
  Char123LocaleChar125publicIndexRoute: typeof Char123LocaleChar125publicIndexRoute
}

const Char123LocaleChar125publicRouteRouteChildren: Char123LocaleChar125publicRouteRouteChildren =
  {
    Char123LocaleChar125publicLoginRoute: Char123LocaleChar125publicLoginRoute,
    Char123LocaleChar125publicIndexRoute: Char123LocaleChar125publicIndexRoute,
  }

const Char123LocaleChar125publicRouteRouteWithChildren =
  Char123LocaleChar125publicRouteRoute._addFileChildren(
    Char123LocaleChar125publicRouteRouteChildren,
  )

interface Char123LocaleChar125AppRouteRouteChildren {
  Char123LocaleChar125AppAccountRoute: typeof Char123LocaleChar125AppAccountRoute
  Char123LocaleChar125AppSettingsRoute: typeof Char123LocaleChar125AppSettingsRoute
  Char123LocaleChar125AppSharedWishlistsRoute: typeof Char123LocaleChar125AppSharedWishlistsRoute
  Char123LocaleChar125AppIndexRoute: typeof Char123LocaleChar125AppIndexRoute
  Char123LocaleChar125AppWishlistsIdRoute: typeof Char123LocaleChar125AppWishlistsIdRoute
  Char123LocaleChar125AppWishlistsIndexRoute: typeof Char123LocaleChar125AppWishlistsIndexRoute
}

const Char123LocaleChar125AppRouteRouteChildren: Char123LocaleChar125AppRouteRouteChildren =
  {
    Char123LocaleChar125AppAccountRoute: Char123LocaleChar125AppAccountRoute,
    Char123LocaleChar125AppSettingsRoute: Char123LocaleChar125AppSettingsRoute,
    Char123LocaleChar125AppSharedWishlistsRoute:
      Char123LocaleChar125AppSharedWishlistsRoute,
    Char123LocaleChar125AppIndexRoute: Char123LocaleChar125AppIndexRoute,
    Char123LocaleChar125AppWishlistsIdRoute:
      Char123LocaleChar125AppWishlistsIdRoute,
    Char123LocaleChar125AppWishlistsIndexRoute:
      Char123LocaleChar125AppWishlistsIndexRoute,
  }

const Char123LocaleChar125AppRouteRouteWithChildren =
  Char123LocaleChar125AppRouteRoute._addFileChildren(
    Char123LocaleChar125AppRouteRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125publicRouteRoute: typeof Char123LocaleChar125publicRouteRouteWithChildren
  Char123LocaleChar125AppRouteRoute: typeof Char123LocaleChar125AppRouteRouteWithChildren
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125publicRouteRoute:
      Char123LocaleChar125publicRouteRouteWithChildren,
    Char123LocaleChar125AppRouteRoute:
      Char123LocaleChar125AppRouteRouteWithChildren,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  AuthSplatServerRoute: AuthSplatServerRoute,
  TrpcSplatServerRoute: TrpcSplatServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
