services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    networks:
      - db-network
      - redis-network
    command: sleep infinity
    environment:
      DATABASE_URL: postgresql://postgres:mysecretpassword@db:5432/postgres
      REDIS_URL: redis://redis:6379
      TEST_AUTH: true
      BETTER_AUTH_SECRET: abcdefghijklmnopqrstuvwxyz123456789
      BETTER_AUTH_ALLOWED_HOSTS: '["localhost:*", "127.0.0.1:*"]'
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:17
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - db-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-t", "10"]
      interval: 1s
      timeout: 10s
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mysecretpassword}
  redis:
    image: redis:8
    restart: unless-stopped
    networks:
      - redis-network

networks:
  db-network:
  redis-network:

volumes:
  db-data:
